"""update_todo_model

Revision ID: 82f5e03e02dd
Revises: e33387cd398f
Create Date: 2026-06-30 13:40:43.592017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f5e03e02dd'
down_revision: Union[str, Sequence[str], None] = 'e33387cd398f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('status', sa.String(), nullable=True))
    op.add_column('todos', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('todos', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('todos', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('todos', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('todos', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('todos', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('todos', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_todos_title'), 'todos', ['title'], unique=False)
    op.create_foreign_key(None, 'todos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_index(op.f('ix_todos_title'), table_name='todos')
    op.alter_column('todos', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('todos', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('todos', 'user_id')
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'created_at')
    op.drop_column('todos', 'due_date')
    op.drop_column('todos', 'priority')
    op.drop_column('todos', 'status')
    # ### end Alembic commands ###
